### ISSUE TITLE
EROR : Cannot read the property 'match'

### ISSUE THREAD

**Issue by Harsh-beep** [Urbaexyz/whatsapp-bot#14]
![](https://i.gyazo.com/e7c82e3e90205136477d0b806a7b9fcd.png)

![](https://i.gyazo.com/9e51704fc02e6e99b5d612b614d02ae6.png)

**Comment by Urbaexyz** [comment]
send screenshot when you type in whatsapp for that error

**Comment by Harsh-beep** [comment]
there is no error in whatsapp or bot. It's just on console.

**Comment by Urbaexyz** [comment]
> there is no error in whatsapp or bot. It's just on console.

try change chats.match into chats.includes
tell us if it's fixed the problem

**Comment by Harsh-beep** [comment]
× Session data most likely expired due to manual host account logout. Please re-authenticate this session.
BOT is down for everyone now...

> try change chats.match into chats.includes
> tell us if it's fixed the problem

I did the changes... I'll let you know later..

**Comment by Harsh-beep** [comment]
Different error
![image](https://user-images.githubusercontent.com/76943884/133369982-928f3c66-4d33-4dbb-9832-24b6f4fd324d.png)

**Comment by gamingrkp** [comment]
> Different error
> ![image](https://user-images.githubusercontent.com/76943884/133369982-928f3c66-4d33-4dbb-9832-24b6f4fd324d.png)
> ![image](https://user-images.githubusercontent.com/76943884/133370153-1c9bd396-96fe-44ea-9b49-2ece5a417f46.png)

try this ```if (chats.match(new RegExp(/(https:\/\/chat.whatsapp.com)/gi)))```

**Comment by gamingrkp** [comment]
> > there is no error in whatsapp or bot. It's just on console.
> 
> try change chats.match into chats.includes
> tell us if it's fixed the problem

itu error karena regex coba cari aja apa itu regex

**Comment by Harsh-beep** [comment]
> > Different error
> > ![image](https://user-images.githubusercontent.com/76943884/133369982-928f3c66-4d33-4dbb-9832-24b6f4fd324d.png)
> > ![image](https://user-images.githubusercontent.com/76943884/133370153-1c9bd396-96fe-44ea-9b49-2ece5a417f46.png)
> 
> try this `if (chats.match(new RegExp(/(https:\/\/chat.whatsapp.com)/gi)))`

I did it. I'll let you know if it occurs again.. Thanks

**Comment by Harsh-beep** [comment]
> try this `if (chats.match(new RegExp(/(https:\/\/chat.whatsapp.com)/gi)))`

![image](https://user-images.githubusercontent.com/76943884/133466876-28e6086d-9b06-45c1-8772-9947aa2f4089.png)
![image](https://user-images.githubusercontent.com/76943884/133467062-eff97380-b049-4f8d-bf18-687711b9f8eb.png)
Same

**Comment by Urbaexyz** [comment]
> > try this `if (chats.match(new RegExp(/(https:\/\/chat.whatsapp.com)/gi)))`
> 
> ![image](https://user-images.githubusercontent.com/76943884/133466876-28e6086d-9b06-45c1-8772-9947aa2f4089.png)
> ![image](https://user-images.githubusercontent.com/76943884/133467062-eff97380-b049-4f8d-bf18-687711b9f8eb.png)
> Same

why you close this issue?
is it fixed now?

**Comment by Harsh-beep** [comment]
> > 
> > try this `if (chats.match(new RegExp(/(https:\/\/chat.whatsapp.com)/gi)))`
> 
> I did it. I'll let you know if it occurs again.. Thanks

Yes, It's fixed.. I edited code to
`if (isGroupMsg && GroupLinkDetector && !isGroupAdmins && !isOwner && oneLink == 0){
            try {
				if (chats.match(new RegExp(/(https:\/\/chat.whatsapp.com)/gi))) {
					oneLink = 1; const gplka = await aruga.inviteInfo(chats)
					if (gplka) {
						console.log(color('[BAN]', 'red'), color('Group link detected, removing participant...', 'yellow'))
						await aruga.reply(from, '*[GROUP LINK DETECTOR]*\nYou sent a group chat link, sorry you got kicked from the group..:( ', id).then(async () => {await aruga.removeParticipant(groupId, user);return oneLink = 0 })
					} else { console.log(color('[ALERT]', 'yellow'), color('Invalid group link received...', 'yellow'));oneLink = 0 }
				}
			} catch (error) { return oneLink = 0 }
		}`

**Comment by Urbaexyz** [comment]
> > > try this `if (chats.match(new RegExp(/(https:\/\/chat.whatsapp.com)/gi)))`
> > 
> > 
> > I did it. I'll let you know if it occurs again.. Thanks
> 
> Yes, It's fixed.. I edited code to `if (isGroupMsg && GroupLinkDetector && !isGroupAdmins && !isOwner && oneLink == 0){ try { if (chats.match(new RegExp(/(https:\/\/chat.whatsapp.com)/gi))) { oneLink = 1; const gplka = await aruga.inviteInfo(chats) if (gplka) { console.log(color('[BAN]', 'red'), color('Group link detected, removing participant...', 'yellow')) await aruga.reply(from, '*[GROUP LINK DETECTOR]*\nYou sent a group chat link, sorry you got kicked from the group..:( ', id).then(async () => {await aruga.removeParticipant(groupId, user);return oneLink = 0 }) } else { console.log(color('[ALERT]', 'yellow'), color('Invalid group link received...', 'yellow'));oneLink = 0 } } } catch (error) { return oneLink = 0 } }`
> 
> ![image](https://user-images.githubusercontent.com/76943884/133917986-25220b44-caf5-4b18-9912-f7f11bea5655.png)

okayyy
