### ISSUE TITLE
section start problems

### ISSUE THREAD

**Issue by Stive889** [Urbaexyz/whatsapp-bot#15]
when trying to start the bot the following error appears.

![image](https://user-images.githubusercontent.com/26675985/133355392-a4639c09-e698-4892-a69a-b6cd90842f06.png)

even if the latest version is used without modifying.

**Comment by Urbaexyz** [comment]
> when trying to start the bot the following error appears.
> 
> ![image](https://user-images.githubusercontent.com/26675985/133355392-a4639c09-e698-4892-a69a-b6cd90842f06.png)
> 
> even if the latest version is used without modifying.

use this

`npm i --save @open-wa/wa-automate@latest`

**Comment by Stive889** [comment]
thx bro
