### ISSUE TITLE
Not working in private message

### ISSUE THREAD

**Issue by Harsh-beep** [Urbaexyz/whatsapp-bot#16]
![image](https://user-images.githubusercontent.com/76943884/133883131-3c992835-9166-49a2-86b8-deaa18c0085f.png)
![image](https://user-images.githubusercontent.com/76943884/133883133-15c1feba-856f-42f0-ae19-4475c91e64f2.png)
I don't know this error comes when someone uses the bot in dm
It works fine in groups..

**Comment by Urbaexyz** [comment]
> ![image](https://user-images.githubusercontent.com/76943884/133883131-3c992835-9166-49a2-86b8-deaa18c0085f.png)
> ![image](https://user-images.githubusercontent.com/76943884/133883133-15c1feba-856f-42f0-ae19-4475c91e64f2.png)
> I don't know this error comes when someone uses the bot in dm
> It works fine in groups..

sorry, i don't have phone to check this repo bruh

for that's error, just wait, it's error from rest api

**Comment by Harsh-beep** [comment]
> 
> sorry, i don't have phone to check this repo bruh
> 
> for that's error, just wait, it's error from rest api

It was a error from wa-automate...
It's fixed now...
