### ISSUE TITLE
Menu .math / .mtk

### ISSUE THREAD

**Issue by Poks-A78** [Urbaexyz/whatsapp-bot#25]
Tidak bisa memberikan jawaban dan Tidak menambahkan point

Leaderboard difilter berdasarkan angka ( nomor ) bukan nama ({pushname})

**Comment by Urbaexyz** [comment]
> Tidak bisa memberikan jawaban dan Tidak menambahkan point
> 
> Leaderboard difilter berdasarkan angka ( nomor ) bukan nama ({pushname})

sorry lama respon
cuman baru nemu caranya
ini leaderboard sudah diganti jadi pushname
[c79b55bcef27d73d04cda82501c0f30f78f147c5](https://github.com/Urbaexyz/whatsapp-bot/commit/c79b55bcef27d73d04cda82501c0f30f78f147c5)
