### ISSUE TITLE
Req emojisticker yg work ngab hehe

### ISSUE THREAD

**Issue by NeoxyzZ** [Urbaexyz/whatsapp-bot#30]
udh di encodeURIComponent(args[0]) tetep ga ke detect di console

**Comment by Urbaexyz** [comment]
> udh di encodeURIComponent(args[0]) tetep ga ke detect di console

susah bat dah heran wkwk

**Comment by Urbaexyz** [comment]
> udh di encodeURIComponent(args[0]) tetep ga ke detect di console

akowkwow cok udh di fixed:v
sorry yaa sorry telatnya kebangetan akwowko
