### ISSUE TITLE
ERROR, The session is invalid

### ISSUE THREAD

**Issue by Poks-A78** [Urbaexyz/whatsapp-bot#31]
![Uploading 16354293713931664438347006962696.jpg…]()

**Comment by Poks-A78** [comment]
https://ibb.co/6YnG9zh - ini link fotonya

Taoilan errornya:
√ Use this easy pre-filled link to report an issue: https://github.com/open-wa/wa-automate-nodejs/issues/new?template=bug_report.yaml&debug_info=%7B%0A%20%20%22WA_VERSION%22:%20%222.2142.12%22,%0A%20%20%22WA_AUTOMATE_VERSION%22:%20%224.23.1%20UPDATE%20AVAILABLE:%204.23.6%22,%0A%20%20%22BROWSER_VERSION%22:%20%22HeadlessChrome/95.0.4638.69%22,%0A%20%20%22START_TS%22:%201635746886745%0A%7D&environment=-%20OS:%20Windows%2010%0A-%20Node:%2014.16.1%0A-%20npm:%20%0A
× Session data most likely expired due to manual host account logout. Please re-authenticate this session.


Note:  Tidak menampilkan qr code untuk authenticating

**Comment by Urbaexyz** [comment]
> https://ibb.co/6YnG9zh - ini link fotonya
> 
> Taoilan errornya: √ Use this easy pre-filled link to report an issue: https://github.com/open-wa/wa-automate-nodejs/issues/new?template=bug_report.yaml&debug_info=%7B%0A%20%20%22WA_VERSION%22:%20%222.2142.12%22,%0A%20%20%22WA_AUTOMATE_VERSION%22:%20%224.23.1%20UPDATE%20AVAILABLE:%204.23.6%22,%0A%20%20%22BROWSER_VERSION%22:%20%22HeadlessChrome/95.0.4638.69%22,%0A%20%20%22START_TS%22:%201635746886745%0A%7D&environment=-%20OS:%20Windows%2010%0A-%20Node:%2014.16.1%0A-%20npm:%20%0A × Session data most likely expired due to manual host account logout. Please re-authenticate this session.
> 
> Note: Tidak menampilkan qr code untuk authenticating

delete URBAE.data.json (kalau masih ada)
trus pake command ini
```npm i --save @open-wa/wa-automate@latest```
