### ISSUE TITLE
ChromePathNotSetError

### ISSUE THREAD

**Issue by Aalcantaraxxx** [Urbaexyz/whatsapp-bot#34]
Help me please :(

![image](https://user-images.githubusercontent.com/77713872/141013055-d02eaecb-96bf-4fc7-b50d-316190ca861a.png)

**Comment by Aalcantaraxxx** [comment]
No, i use replit u helped me 8 months ago
![image](https://user-images.githubusercontent.com/77713872/141193968-ef87bdfc-8f82-4a85-93eb-4899508e784f.png)

**Comment by Aalcantaraxxx** [comment]
What can i do? @Urbaexyz  :(

**Comment by Urbaexyz** [comment]
> What can i do? @Urbaexyz :(

sorry for late reply, i don't have phone lmao

**Comment by Aalcantaraxxx** [comment]
> > What can i do? @Urbaexyz :(
> 
> sorry for late reply, i don't have phone lmao

Don´t worry, u have now? i need help 😥

**Comment by Urbaexyz** [comment]
> > > What can i do? @Urbaexyz :(
> > 
> > 
> > sorry for late reply, i don't have phone lmao
> 
> Don´t worry, u have now? i need help disappointed_relieved

bruh i try it and it have same problem
sorry
