### ISSUE TITLE
selalu mati di heroku

### ISSUE THREAD

**Issue by Adiixyz** [Urbaexyz/whatsapp-bot#44]
![Screenshot_2021-12-09-09-49-02-48](https://user-images.githubusercontent.com/82200440/145319674-5f91be6c-be48-4118-8d92-d9a17c413cc1.png)

ini fixnya gimana?

**Comment by Urbaexyz** [comment]
> ![Screenshot_2021-12-09-09-49-02-48](https://user-images.githubusercontent.com/82200440/145319674-5f91be6c-be48-4118-8d92-d9a17c413cc1.png)
> 
> ini fixnya gimana?

upgrade gan herokunya
itu dynosnya ga cukup tuh makanya selalu mati

**Comment by Adiixyz** [comment]
> > ![Screenshot_2021-12-09-09-49-02-48](https://user-images.githubusercontent.com/82200440/145319674-5f91be6c-be48-4118-8d92-d9a17c413cc1.png)
> > ini fixnya gimana?
> 
> upgrade gan herokunya itu dynosnya ga cukup tuh makanya selalu mati

sip
