### ISSUE TITLE
Can't find module 'mime-types'

### ISSUE THREAD

**Issue by Poks-A78** [Urbaexyz/whatsapp-bot#49]
![Uploading 16406095823768173474689529015565.jpg…]()

**Comment by Urbaexyz** [comment]
link fotonya rusak

**Comment by Urbaexyz** [comment]
saya aman aja bang

![image](https://user-images.githubusercontent.com/89589243/147513688-d94946cc-2fb9-4b7a-b45b-f9c95507454b.png)
