### ISSUE TITLE
Target Closed..

### ISSUE THREAD

**Issue by Harsh-beep** [Urbaexyz/whatsapp-bot#5]
![Screenshot (69)](https://user-images.githubusercontent.com/76943884/131209870-dc5ca45d-4d62-4d50-bb30-e20f43165462.png)
Why does this occur?

**Comment by Urbaexyz** [comment]
> ![Screenshot (69)](https://user-images.githubusercontent.com/76943884/131209870-dc5ca45d-4d62-4d50-bb30-e20f43165462.png)
> Why does this occur?

`npm uninstall -i sharp`

then

`npm install -i sharp@0.28.3`

or you can clone with a new one, i have update this script
