### ISSUE TITLE
help

### ISSUE THREAD

**Issue by muhammadzakizn** [Urbaexyz/whatsapp-bot#54]
error pas run npm start

sebelumnya begini :
![Screenshot (555)](https://user-images.githubusercontent.com/73261827/148677741-a8241542-226f-4253-91db-c47423be3806.png)

lalu bbrp detik lngsung gini :
![Screenshot (556)](https://user-images.githubusercontent.com/73261827/148677755-42576545-8ebd-4b2f-8d93-fc3ce73acd29.png)

**Comment by Urbaexyz** [comment]
@Urbaexyz ```npm i --save @open-wa/wa-automate@latest```

**Comment by muhammadzakizn** [comment]
> @muhammadzakizn `npm i --save @open-wa/wa-automate@latest`

masih
![Screenshot (580)](https://user-images.githubusercontent.com/73261827/148703837-6d7ca8a8-6e43-495e-ab6b-88de8fba3f14.png)

**Comment by gamingrkp** [comment]
> error pas run npm start
> 
> sebelumnya begini : ![Screenshot (555)](https://user-images.githubusercontent.com/73261827/148677741-a8241542-226f-4253-91db-c47423be3806.png)
> 
> lalu bbrp detik lngsung gini : ![Screenshot (556)](https://user-images.githubusercontent.com/73261827/148677755-42576545-8ebd-4b2f-8d93-fc3ce73acd29.png)

Coba install python

**Comment by muhammadzakizn** [comment]
> > error pas run npm start
> > sebelumnya begini : ![Screenshot (555)](https://user-images.githubusercontent.com/73261827/148677741-a8241542-226f-4253-91db-c47423be3806.png)
> > lalu bbrp detik lngsung gini : ![Screenshot (556)](https://user-images.githubusercontent.com/73261827/148677755-42576545-8ebd-4b2f-8d93-fc3ce73acd29.png)
> 
> Coba install python

masih, atau pythonnya di tmbhain path edit variabel?
![Screenshot (583)](https://user-images.githubusercontent.com/73261827/148707144-61204c78-b393-4e5d-be34-ecd8710df73c.png)
![Screenshot (582)](https://user-images.githubusercontent.com/73261827/148707158-9ae649dc-5a11-44ae-9604-b530b38ebea1.png)

**Comment by Urbaexyz** [comment]
> > @muhammadzakizn `npm i --save @open-wa/wa-automate@latest`
> 
> masih ![Screenshot (580)](https://user-images.githubusercontent.com/73261827/148703837-6d7ca8a8-6e43-495e-ab6b-88de8fba3f14.png)

iya cokk, repo yg lain juga bgini
gw juga lagi nanya si SHAH di discord
BocchiBot juga bug kek gtu cuy

**Comment by muhammadzakizn** [comment]
> > > @muhammadzakizn `npm i --save @open-wa/wa-automate@latest`
> > 
> > masih ![Screenshot (580)](https://user-images.githubusercontent.com/73261827/148703837-6d7ca8a8-6e43-495e-ab6b-88de8fba3f14.png)
> 
> iya cokk, repo yg lain juga bgini
> gw juga lagi nanya si SHAH di discord
> BocchiBot juga bug kek gtu cuy

Jadi, solusinya gimana?

**Comment by muhammadzakizn** [comment]
@Urbaexyz Dapat berita dari sebelah ternyata ada sabotase data modul color.js [ versi v1.4.44-liberty-2 - 08/01/2022 ] yang diteruskan ke github & npm😥
[ATTENTION! Dev corrupts NPM libs 'colors' and 'faker' breaking thousands of apps](https://www.bleepingcomputer.com/news/security/dev-corrupts-npm-libs-colors-and-faker-breaking-thousands-of-apps) 

- Cara fix nya :
[Fix spam in console and wm](https://github.com/Nurutomo/wabot-aq/pull/1014)
g tau bgmna caranya...

**Comment by gamingrkp** [comment]
> @Urbaexyz Dapat berita dari repo sebelah ternyata ada sabotase data modul color.js [ versi v1.4.44-liberty-2 - 08/01/2022 ] yang diteruskan ke github & npm😥 [ATTENTION! Dev corrupts NPM libs 'colors' and 'faker' breaking thousands of apps](https://www.bleepingcomputer.com/news/security/dev-corrupts-npm-libs-colors-and-faker-breaking-thousands-of-apps)
> 
> Cara fix nya : [Fix spam in console and wm](https://github.com/Nurutomo/wabot-aq/pull/1014) g tau bgmna caranya ngefix sendiri, bantu w dong..😅

tunggu aja ownernya / lu ganti kesini  https://github.com/Urbaexyz/whatsapp-bot/blob/main/package.json, tambahin ini "colors": "1.4.0",

**Comment by Urbaexyz** [comment]
> @Urbaexyz Dapat berita dari repo sebelah ternyata ada sabotase data modul color.js [ versi v1.4.44-liberty-2 - 08/01/2022 ] yang diteruskan ke github & npmdisappointed_relieved [ATTENTION! Dev corrupts NPM libs 'colors' and 'faker' breaking thousands of apps](https://www.bleepingcomputer.com/news/security/dev-corrupts-npm-libs-colors-and-faker-breaking-thousands-of-apps)
> 
> Cara fix nya : [Fix spam in console and wm](https://github.com/Nurutomo/wabot-aq/pull/1014) g tau bgmna caranya ngefix sendiri, bantu w dong..sweat_smile

udh di fixed

**Comment by gamingrkp** [comment]
> > > error pas run npm start
> > > sebelumnya begini : ![Screenshot (555)](https://user-images.githubusercontent.com/73261827/148677741-a8241542-226f-4253-91db-c47423be3806.png)
> > > lalu bbrp detik lngsung gini : ![Screenshot (556)](https://user-images.githubusercontent.com/73261827/148677755-42576545-8ebd-4b2f-8d93-fc3ce73acd29.png)
> > 
> > 
> > Coba install python
> 
> masih, atau pythonnya di tmbhain path edit variabel? ![Screenshot (583)](https://user-images.githubusercontent.com/73261827/148707144-61204c78-b393-4e5d-be34-ecd8710df73c.png) ![Screenshot (582)](https://user-images.githubusercontent.com/73261827/148707158-9ae649dc-5a11-44ae-9604-b530b38ebea1.png)

seharusnya pas install python lu centang set to variable nnti langsung auto ama py nya
