### ISSUE TITLE
Multi device detected

### ISSUE THREAD

**Issue by agusbragas** [Urbaexyz/whatsapp-bot#74]
Mungkin yang lain sudah pernah mengalami dan berhasil mengatasi masalah ini..
pesan error muncul saat scan QR Code:
Multi-Device detected, please set multiDevice to true in your config or add the --multi-device flag

mohon bantuannya.. terima kasih..

**Comment by Urbaexyz** [comment]
> Mungkin yang lain sudah pernah mengalami dan berhasil mengatasi masalah ini.. pesan error muncul saat scan QR Code: Multi-Device detected, please set multiDevice to true in your config or add the --multi-device flag
> 
> mohon bantuannya.. terima kasih..

![Screenshot_2022-02-21-19-00-36-84_61c78dc80ee02b53007c815fefe993e3](https://user-images.githubusercontent.com/89589243/154952761-09e34ad9-75cb-4f42-8b40-27fb2bd0d9b8.jpg)

Saya aman bg

**Comment by agusbragas** [comment]
runing nya di termux ya?

**Comment by agusbragas** [comment]
saya running di cmd
apa beda?

**Comment by agusbragas** [comment]
![image](https://user-images.githubusercontent.com/7631047/154958733-0cdc0be4-fda5-427a-b62b-837ce1f653ad.png)

**Comment by Urbaexyz** [comment]
> runing nya di termux ya?

Ubuntu
