### ISSUE TITLE
drawbacks with keeping the bot active

### ISSUE THREAD

**Issue by Stive889** [Urbaexyz/whatsapp-bot#89]
hello Urbaexyz, I hope you are well, I have a problem with keeping the section active after restarting, it tells me about an error with the multi device, but I don't know what to do in this case, every time I have to turn it on, I have to go back to sync with qr code

![1](https://user-images.githubusercontent.com/26675985/164128774-211880e4-ea14-4eb3-8d77-87c0d91d1931.jpg)

![2](https://user-images.githubusercontent.com/26675985/164128771-5c10541f-78ea-4e73-b65c-9006c04bb180.jpg)

**Comment by Urbaexyz** [comment]
> hello Urbaexyz, I hope you are well, I have a problem with keeping the section active after restarting, it tells me about an error with the multi device, but I don't know what to do in this case, every time I have to turn it on, I have to go back to sync with qr code
> 
> ![1](https://user-images.githubusercontent.com/26675985/164128774-211880e4-ea14-4eb3-8d77-87c0d91d1931.jpg)
> 
> ![2](https://user-images.githubusercontent.com/26675985/164128771-5c10541f-78ea-4e73-b65c-9006c04bb180.jpg)

That's bug i think from original whatsapp
'cause now WhatsApp force using MD, that's why you get that error

**Comment by Urbaexyz** [comment]
> hello Urbaexyz, I hope you are well, I have a problem with keeping the section active after restarting, it tells me about an error with the multi device, but I don't know what to do in this case, every time I have to turn it on, I have to go back to sync with qr code
> 
> ![1](https://user-images.githubusercontent.com/26675985/164128774-211880e4-ea14-4eb3-8d77-87c0d91d1931.jpg)
> 
> ![2](https://user-images.githubusercontent.com/26675985/164128771-5c10541f-78ea-4e73-b65c-9006c04bb180.jpg)

https://github.com/Urbaexyz/whatsapp-bot/blob/main/function/index.js

> hello Urbaexyz, I hope you are well, I have a problem with keeping the section active after restarting, it tells me about an error with the multi device, but I don't know what to do in this case, every time I have to turn it on, I have to go back to sync with qr code
> 
> ![1](https://user-images.githubusercontent.com/26675985/164128774-211880e4-ea14-4eb3-8d77-87c0d91d1931.jpg)
> 
> ![2](https://user-images.githubusercontent.com/26675985/164128771-5c10541f-78ea-4e73-b65c-9006c04bb180.jpg)

https://github.com/Urbaexyz/whatsapp-bot/commit/9065169fe423fbb0137aadab6821c646a62b0020

**Comment by Stive889** [comment]
Thank you very much, I tried the change and it worked, I had to synchronize it twice but in the second time it was already authenticated.
