### ISSUE TITLE
I don't know error...

### ISSUE THREAD

**Issue by Harsh-beep** [Urbaexyz/whatsapp-bot#9]
![Screenshot (76)](https://user-images.githubusercontent.com/76943884/132392151-eb3d792d-1e5f-4f08-9cf1-58527fe56d36.png)
I don't know what to do.. It happens sometime.. Help..
It's too long error, can't fit in a screenshot

**Comment by Urbaexyz** [comment]
> ![Screenshot (76)](https://user-images.githubusercontent.com/76943884/132392151-eb3d792d-1e5f-4f08-9cf1-58527fe56d36.png)
> I don't know what to do.. It happens sometime.. Help..
> It's too long error, can't fit in a screenshot

i don't think i create for that feature
have a screenshot on HandleMsg for that feature?

**Comment by Harsh-beep** [comment]
> i don't think i create for that feature
> have a screenshot on HandleMsg for that feature?

I added that feature..
I thought this error occured automatically
It didn't occur because of  command i guess maybe..
![image](https://user-images.githubusercontent.com/76943884/132724001-3b09f2e2-792b-4669-86b3-fd171bc5674b.png)

**Comment by Urbaexyz** [comment]
> > i don't think i create for that feature
> > have a screenshot on HandleMsg for that feature?
> 
> I added that feature..
> I thought this error occured automatically
> It didn't occur because of command i guess maybe..
> ![image](https://user-images.githubusercontent.com/76943884/132724001-3b09f2e2-792b-4669-86b3-fd171bc5674b.png)

maybe it's error from rest api, but console log show error from axios

**Comment by Harsh-beep** [comment]
> maybe it's error from rest api, but console log show error from axios
Well it isn't occurning anymore.. So it's fine for now
