### ISSUE TITLE
rzkyfdlh-api token wrong

### ISSUE THREAD

**Issue by bowbow13** [Urbaexyz/whatsapp-bot#91]
Mohon bantuannya gan. Sudah coba request token lewat cara yg bawah, tp masih belum dpt respon

SyntaxError: Invalid Token: Token Wrong! , get token here https://wa.me/6288212146809?text=!gettoken

**Comment by Urbaexyz** [comment]
> Mohon bantuannya gan. Sudah coba request token lewat cara yg bawah, tp masih belum dpt respon
> 
> SyntaxError: Invalid Token: Token Wrong! , get token here https://wa.me/6288212146809?text=!gettoken

Fixed https://github.com/Urbaexyz/whatsapp-bot/commit/d6db7367e6999d646e73c9ca125187f9b420c86f
Sorry typo
